In [8]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Load dataset
df = kagglehub.dataset_load(
    KaggleDatasetAdapter.PANDAS,
    'jackksoncsie/spam-email-dataset',
    'emails.csv',
)

df.head()

                                                text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [9]:
# Check ratio
df['spam'].value_counts()

spam
0    4360
1    1368
Name: count, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split

# Clean X
df['text'] = df['text'].str.removeprefix('Subject: ')

# Assign X, y
X = df['text']
y = df['spam']

# Split train, test
X_train, X_test, y_train, y_test = train_test_split(
	X, y, test_size=0.2, random_state=11, stratify=y
)

df.head()

                                                text  spam
0  naturally irresistible your corporate identity...     1
1  the stock trading gunslinger  fanny is merrill...     1
2  unbelievable new homes made easy  im wanting t...     1
3  4 color printing special  request additional i...     1
4  do not have money , get software cds from here...     1